### ISSUE TITLE
Revise README.md to refer to main.ts as common alternative to boot.ts.

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/angular2-carbonldp#3]
In the README.md it says "In the file where you are bootstrapping your Angular2 application (commonly boot.ts), you need to initialize the active Carbon's context you are going to use across your application."

I would put "(commonly boot.ts or main.ts). It seems to be more common in the Angular 2 documentation that main.ts is used.

See, for example: https://angular.io/docs/ts/latest/guide/router.html

**Comment by MiguelAraCo** [comment]
You are right. In prior versions it was named `boot.ts`, but if they are changing the naming convention we should change it too.

**Comment by alvaro9210** [comment]
Fixed in #11 
The final versions states: 
"In the bootstrapping file of your Angular2 application (commonly main.ts), you need to initialize the..."
