### ISSUE TITLE
Update angular2-carbonldp to use Angular 2.0.0 final

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/angular2-carbonldp#5]
Using Angular 2.0.0 final, you get the following errors:

npm WARN angular2-carbonldp@0.3.2 requires a peer of @angular/common@2.0.0-rc.5 but none was installed.
npm WARN angular2-carbonldp@0.3.2 requires a peer of @angular/core@2.0.0-rc.5 but none was installed.
npm WARN angular2-carbonldp@0.3.2 requires a peer of @angular/router@3.0.0-rc.2 but none was installed.
npm WARN angular2-carbonldp@0.3.2 requires a peer of carbonldp@^0.37.0 but none was installed.
npm WARN angular2-carbonldp@0.3.2 requires a peer of rxjs@5.0.0-beta.6 but none was installed.

**Comment by MiguelAraCo** [comment]
Version `0.4.1` uses angular 2.0.2
